# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_controller', '0004_auto_20171122_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiontb',
            name='kind_code',
            field=models.BigIntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='visiontb',
            name='up_kind_code',
            field=models.BigIntegerField(default=-1),
        ),
    ]
