# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('batch_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionTb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(max_length=10)),
                ('image_url', models.CharField(max_length=255)),
                ('color_rgb', models.CharField(max_length=255)),
                ('color_score', models.CharField(max_length=255)),
                ('color_fraction', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('label_score', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='batch_controller.PostTb')),
            ],
            options={
                'db_table': 'vision_tb',
                'managed': True,
            },
        ),
    ]
