# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-19 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visiontb',
            name='post',
        ),
        migrations.AddField(
            model_name='visiontb',
            name='post_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
