# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 13:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision_controller', '0003_visiontb_happen_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiontb',
            name='happen_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
