# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'image_tb',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PostTb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('desertion_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('feature', models.CharField(blank=True, max_length=255, null=True)),
                ('gender_type', models.CharField(blank=True, max_length=255, null=True)),
                ('happen_date', models.DateTimeField(blank=True, null=True)),
                ('happen_gungu_code', models.BigIntegerField(blank=True, null=True)),
                ('happen_place', models.CharField(blank=True, max_length=255, null=True)),
                ('happen_sido_code', models.BigIntegerField(blank=True, null=True)),
                ('helper_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('helper_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hit_count', models.BigIntegerField(blank=True, null=True)),
                ('is_display', models.TextField(blank=True, null=True)),
                ('kind_code', models.BigIntegerField(blank=True, null=True)),
                ('kind_name', models.CharField(blank=True, max_length=255, null=True)),
                ('neuter_type', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_begin_date', models.DateTimeField(blank=True, null=True)),
                ('notice_end_date', models.DateTimeField(blank=True, null=True)),
                ('notice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('post_type', models.CharField(blank=True, max_length=255, null=True)),
                ('shelter_code', models.BigIntegerField(blank=True, null=True)),
                ('shelter_contact', models.CharField(blank=True, max_length=255, null=True)),
                ('shelter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state_type', models.CharField(blank=True, max_length=255, null=True)),
                ('up_kind_code', models.BigIntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post_tb',
                'managed': False,
            },
        ),
    ]
