# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_controller', '0002_bookmarktb_commenttb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BreedTb',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('kind_code', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('kind_name', models.CharField(blank=True, max_length=255, null=True)),
                ('up_kind_code', models.BigIntegerField(blank=True, null=True)),
                ('up_kind_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'breed_tb',
                'managed': False,
            },
        ),
    ]
